# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-09 23:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_auto_20161209_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='owner',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='artists', to=settings.AUTH_USER_MODEL),
        ),
    ]
